# Install the MySQL driver:
#   gem install activerecord-jdbcmysql-adapter
#
# Configure Using Gemfile
# gem 'activerecord-jdbcmysql-adapter'
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: socialbeam_storage_dev
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: socialbeam_storage_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
production:
  adapter: mysql
  encoding: utf8
  database: socialbeam_storage_prod
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
