# Install the MYSQL driver
#   gem install mysql2
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: socialbeam_storage_dev
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: socialbeam_storage_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: socialbeam_storage_prod
  pool: 5
  username: root
  password: prodsb
  socket: /var/run/mysqld/mysqld.sock
