# Install the MySQL driver:
#   gem install activerecord-jdbcmysql-adapter
#
# Configure Using Gemfile
# gem 'activerecord-jdbcmysql-adapter'
development:
  adapter: mysql
  encoding: utf8
  database: socialbeam_storage_dev
  username: root
  password: root
  host: localhost
test:
  adapter: mysql
  encoding: utf8
  database: socialbeam_storage_test
  username: root
  password: root
  host: localhost
production:
  adapter: mysql
  encoding: utf8
  database: socialbeam_storage_prod
  username: root
  password: root
  host: localhost